HAND_FIXES = {"§§§pisala": ["§", "§", "§", "pisala"], "§§§poldne": ["§", "§", "§", "poldne"], "§§§o": ["§", "§", "§", "o"],
              "§§§mimi": ["§", "§", "§", "mimi"], "§§§nil": ["§", "§", "§", "nil"], "§§§ela": ["§", "§", "§", "ela"],
              "sam§§§": ["sam", "§", "§", "§"], "globač§§§": ["globač", "§", "§", "§"], "sin.": ["sin", "."],
              "§§§oveduje": ["§", "§", "§", "oveduje"],  "na§§§": ["na", "§", "§", "§"], "§§§ka§§§": ["§", "§", "§", "ka", "§", "§", "§"],
              "§§§e§§§": ["§", "§", "§", "e", "§", "§", "§"], "§§§": ["§", "§", "§"], "ljubezni.": ["ljubezni", "."],
              "st.": ["st", "."], "S.": ["S", "."], "pr.": ["pr", "."], "n.": ["n", "."],
              "19:30": ["19", ":", "30"], "6:35": ["6", ":", "35"], "itd.": ["itd", "."], "Sv.": ["Sv", "."],
              "npr.": ["npr", "."], "sv.": ["sv", "."], "12:00": ["12", ":", "00"], "sram'vali": ["sram", "'", "vali"],
              "18:00": ["18", ":", "00"], "J.": ["J", "."], "5:45": ["5", ":", "45"],
              "9.00h": ["9", ".", "00h"], "H.": ["H", "."], "7:10": ["7", ":", "10"],
              "g.": ["g", "."], "Oz.": ["Oz", "."], "20:00": ["20", ":", "00"], "17.4.2010": ["17.", "4.", "2010"],
              "ga.": ["ga", "."], "prof.": ["prof", "."], "6:45": ["6", ":", "45"],
              "tj.": ["tj", "."], "Prof.": ["Prof", "."], "9:18": ["9", ":", "18"], "ipd.": ["ipd", "."],
              "št.": ["št", "."], "oz.": ["oz", "."], "R.": ["R", "."], "13:30": ["13", ":", "30"],
              "...": [".", ".", "."], "plavali.": ["plavali", "."], "[XImeX]": ["[", "XImeX", "]"],
              "[XimeX]": ["[", "XimeX", "]"], "hipoteze:": ["hipoteze", ":"], "prehrano?": ["prehrano", "?"],
              "68-letna": ["68", "-", "letna"], "pojma:": ["pojma", ":"], "[XKrajX]": ["[", "XKrajX", "]"],
              "3/4": ["3", "/", "4"], "I-phonea": ["I", "-", "phonea"], "kredita:": ["kredita", ":"],
              "[XFakultetaX]": ["[", "XFakultetaX", "]"], "športno-eleganten": ["športno", "-", "eleganten"],
              "[XStudijskaSmerX]": ["[", "XStudijskaSmerX", "]"], "[XNaslovX]": ["[", "XNaslovX", "]"],
              "(tudi": ["(", "tudi"], "kupujem)": ["kupujem", ")"], "[XPriimekX]": ["[", "XPriimekX", "]"],
              "[XPodjetjeX]": ["[", "XPodjetjeX", "]"], "Zagreb,": ["Zagreb", ","], "Budimpešto.": ["Budimpešto", "."],
              "žalost.": ["žalost", "."], "....": [".", ".", ".", "."], "[XStevilkaX]": ["[", "XStevilkaX", "]"],
              "e-naslov": ["e", "-", "naslov"], "[XEnaslovX]": ["[", "XEnaslovX", "]"], "e-pošto": ["e", "-", "pošto"],
              "[XDatumX]": ["[", "XDatumX", "]"], "eno-sobno": ["eno", "-", "sobno"],
              "lgbtq-prijazna": ["lgbtq", "-", "prijazna"], "lgbtq-prijaznega": ["lgbtq", "-", "prijaznega"],
              "Covid-19": ["Covid", "-", "19"], ",,,": [",", ",", ","], "e-maila": ["e", "-", "maila"],
              "T&d": ["T", "&", "d"], "Spider-Man": ["Spider", "-", "Man"], "12-strani": ["12", "-", "strani"],
              "turbo-folk": ["turbo", "-", "folk"], "Cp-čkar": ["Cp", "-", "čkar"], "46-letnik": ["46", "-", "letnik"],
              "40-letna": ["40", "-", "letna"], "18-19h": ["18", "-", "19h"], "[XSvojilniPridevnikX]": ["[", "XSvojilniPridevnikX", "]"],
              "COVID-19": ["COVID", "-", "19"], "'sims'": ["'", "sims", "'"], "2021/22": ["2021", "/", "22"],
              "2020/21": ["2020", "/", "21"], "leto2021/22": ["leto2021", "/", "22"], "H&m": ["H", "&", "m"],
              "high-street": ["high", "-", "street"], "H&M-u": ["H", "&", "M-u"], "H&M": ["H", "&", "M"],
              "srčno-žilnih": ["srčno", "-", "žilnih"], "srčno-žilni": ["srčno", "-", "žilni"], #":))": [":)", ")"],
              "You-Tube-ju": ["You", "-", "Tube-ju"], "37,8%": ["37", ",", "8", "%"], "23,8%": ["23", ",", "8", "%"],
              "17,6%": ["17", ",", "6", "%"], "12,6%": ["12", ",", "6", "%"], "58,2%": ["58", ",", "2", "%"], "76,2%": ["76", ",", "2", "%"],
              ".000": [".", "000"], "slovensko-nemškem": ["slovensko", "-", "nemškem"], "..": [".", "."], "rumeno-bela": ["rumeno", "-", "bela"],
              "košík.cz": ["košík", ".", "cz"], "100%": ["100", "%"], ":()": [":(", ")"]}